<a href="https://colab.research.google.com/github/aayushmiishra/Electrical-Outputs-Prediction/blob/main/eetoccp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.18.0'

In [3]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [4]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [5]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [6]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
ann=tf.keras.models.Sequential()

Adding first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

[link text](https://)Adding second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

In [12]:
ann.compile(optimizer='adam', loss='mean_squared_error')

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 233790.3438
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 206197.6406
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 205784.2031
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205118.8906
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 204461.8438
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 203635.4062
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 202221.4688
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 200922.6719
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 199268.4531
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 197872.4531
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 195879.8438
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 193325.4062
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 191054.3906
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2m

In [14]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step  
[[429.86 431.23]
 [460.39 460.01]
 [463.95 461.14]
 ...
 [471.14 473.26]
 [438.69 438.  ]
 [457.91 463.28]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

ValueError: continuous is not supported